import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/globals.css";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../styles/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>{children}</body>
    </html>
  );
}
