[[redirects]]
  from = "/trend_proxy/*"
  to = "https://trends.google.co.kr/:splat"
  status = 200
  force = true

[[redirects]]
	from = "/news_proxy/*"
  to = "https://www.bbc.com/korean/:splat"
  status = 200
  force = true

	[[redirects]]
	from = "/youtube_proxy/*"
  to = "https://kr.noxinfluencer.com/:splat"
  status = 200
  force = true