[[redirects]]
  from = "/proxy/*"
  to = "https://trends.google.co.kr/:splat"
  status = 200
  force = true

[[redirects]]
	from = "/mostread.json"
  to = "https://www.bbc.com/korean/:splat"
  status = 200
  force = true