[[redirects]]
  from = "/trend_proxy/*"
  to = "https://trends.google.co.kr/:splat"
  status = 200
  force = true

[[redirects]]
	from = "/news_proxy/*"
  to = "https://www.bbc.com/korean/:splat"
  status = 200
  force = true

	[[redirects]]
	from = "/youtube_proxy/*"
  to = "https://kr.noxinfluencer.com/:splat"
  status = 200
  force = true

	[[redirects]]
	from = "/music_proxy/*"
  to = "https://www.melon.com/:splat"
  status = 200
  force = true

	[[redirects]]
	from = "/movie_proxy/*"
  to = "https://movie.daum.net/:splat"
  status = 200
  force = true

	[[redirects]]
	from = "/tv_proxy/*"
  to = "https://search.naver.com/:splat"
  status = 200
  force = true